/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package week2;

import ai.serenade.treesitter.*;
import java.nio.file.*;
import java.nio.charset.*;
import java.io.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
